# Generated by Django 4.2.5 on 2023-09-18 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0002_rename_catgeory_articlecategory_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='article_preferences',
        ),
        migrations.DeleteModel(
            name='ArticleCategory',
        ),
    ]
